### ISSUE TITLE
Implement Local Storage Strategies for Kotlin App

### ISSUE THREAD

**Issue by JeffersonH0501** [MobileDev-SEC02-G21/Wiki#36]
Each mobile app should incorporate at least one strategy for managing local storage to improve performance and user experience, especially in offline scenarios. If existing Sprint 2 functionalities do not necessitate local storage, a new feature or functionality should be added to the app and implemented using local storage techniques. The goal is to optimize app performance and enhance offline capabilities.

**Comment by afgarciab** [comment]
in qr generator and loyaltyCards views the local storage strategy currently are implemented.
