### ISSUE TITLE
Kotlin: Design, implement and justify micro-optimization strategies within the app.

### ISSUE THREAD

**Issue by JeffersonH0501** [MobileDev-SEC02-G21/Wiki#50]
For this you have tofirst evaluate the performance using the profiling tool before  the  micro-optimization  implementation,  then  implement  the  optimization, finally use the profiling tool again to test the modified feature.

**Comment by afgarciab** [comment]
I implemented an optimization in **LoyaltyCardsActivity** to reduce CPU usage and improve the execution time for loading loyalty cards.
