### ISSUE TITLE
Flutter: Design, implement and justify micro-optimization strategies within the app.

### ISSUE THREAD

**Issue by JeffersonH0501** [MobileDev-SEC02-G21/Wiki#51]
Design, implement and justify micro-optimization strategies within the app.For this you have tofirst evaluate the performance using the profiling tool before  the  micro-optimization  implementation,  then  implement  the  optimization, finally use the profiling tool again to test the modified feature.

**Comment by ahernandezo2** [comment]
they are already described and documented
