### ISSUE TITLE
Kotlin: Implement new feature and view in our app with caching strategy

### ISSUE THREAD

**Issue by JeffersonH0501** [MobileDev-SEC02-G21/Wiki#56]
This task entails the development and integration of a new feature and its corresponding user interface within the application. To optimize performance and reduce network load, a caching strategy will be implemented. This will involve storing frequently accessed data locally, allowing the app to quickly retrieve information without relying solely on network requests. This caching mechanism will significantly enhance the overall user experience by providing faster load times and smoother interactions.

**Comment by afgarciab** [comment]
I use the LRU cache to limit the use of recovery password function in order to avoid attacs to the email and data base system
